security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: admin_dashboard  # Redirige vers /admin après connexion réussie
                always_use_default_target_path: false  # N’utilise pas default_target_path en cas d’échec
                failure_path: app_login  # Reste sur /login en cas d’échec
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }
        - { path: ^/employe, roles: ROLE_EMPLOYE }